### Create Role
POST http://localhost:8080/roles
Content-Type: application/json

{
  "roleName": "STUDENT"
}

### Create User
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Mohammed Yasin",
  "email": "bsse1406@iit.du.ac.bd"
}


### Assign Role
POST http://localhost:8080/users/{{userId}}/assign-role/{{roleId}}

### Get User
GET http://localhost:8080/users/{{userId}}